version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for
      # this Jupyter Book so it builds.
      - "jupyter-book config sphinx book/"

# Dependencies required to build your docs
python:
   install:
     - method: pip
       path: .

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
