version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "16"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for
      # this Jupyter Book so it builds.
      - "jupyter-book config sphinx book/"
    post_install:
      - npm install -g @mermaid-js/mermaid-cli
      # Import matplotlib to build the font cache
      # Otherwise, the first time it's imported cell execution
      # can timeout
      - python -c "import matplotlib"

# Dependencies required to build your docs
python:
  install:
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: book/conf.py
  fail_on_warning: true
